require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'DatingApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'DatingAppTests' do
    inherit! :complete
    # Pods for testing
  end

  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        config.build_settings.delete('ARCHS')
      end
    end
  end
end

target 'DatingApp-tvOS' do
  # Pods for DatingApp-tvOS

  target 'DatingApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
